### ISSUE TITLE
IMAGE TO SKETCH CONVERTER

### ISSUE THREAD

**Issue by Richa812** [python-geeks/Automation-scripts#632] opened 2021-10-06 03:10 UTC
## IMAGE TO SKETCH CONVERTER USING PYTHON AND OPENCV

**It is an interesting project where any image can be coverted to a sketch . 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by Richa812** [comment] 2021-10-06 03:10
May I work on this issue?

**Comment by pawangeek** [comment] 2021-10-06 04:21
> May I work on this issue?

Duplicate of #108

**Closed by pawangeek** 2021-10-06 04:21 UTC
Labels: good first issue, hacktoberfest, up-for-grabs
