### ISSUE TITLE
Directory Organizer

### ISSUE THREAD

**Issue by akashydv7** [python-geeks/Automation-scripts#345] opened 2021-07-26 12:36 UTC
## Script Title - dir_organizer
**Brief** - simple script to organize directory by putting different types files in respective folders based on extensions 

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by akashydv7** [comment] 2021-07-26 12:40
Can I work on this ?

**Comment by pawangeek** [comment] 2021-07-28 06:23
Hey @akashydv7, I think the issue is the same as merged by #220 isn't it?

**Comment by akashydv7** [comment] 2021-07-28 07:03
I guess it's the same. Sorry I should have looked for that.

**Closed** 2021-07-28 07:04 UTC
Labels: good first issue, hacktoberfest, up-for-grabs
