### ISSUE TITLE
Plagiarism Detector

### ISSUE THREAD

**Issue by akshitasinghal4444** [python-geeks/Automation-scripts#407] opened 2021-08-24 05:50 UTC
## Script Title - Plagiarism Detector

**Brief** - This script will take 2 files and show the amount (percentage)  of similarity between those files .

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by akshitasinghal4444** [comment] 2021-08-24 05:51
Pleasee assign me this issue : )

**Comment by vipinkatara** [comment] 2021-08-24 11:47
Hey,
 Can you assign this issue to me.This will be my first contribution to open source world.
Thanks in advance

**Comment by akshitasinghal4444** [comment] 2021-08-24 11:52
@vipinkatara  Actually I wanted to work on this issue myself . This would be first issue for me too . You can create your own issue to work on .

**Comment by vipinkatara** [comment] 2021-08-24 12:00
@akshitasinghal4444  okay thanks.

**Comment by pawangeek** [comment] 2021-08-25 06:58
Hey @akshitasinghal4444 this is duplicate of #324

**Closed** 2021-08-25 06:59 UTC
Labels: duplicate
