### ISSUE TITLE
Manage Files

### ISSUE THREAD

**Issue by chauhanarpit09** [python-geeks/Automation-scripts#396] opened 2021-08-22 04:25 UTC
## Script Title -

I would like to create a script to manage files in a particular folder (especially the Download folder)
Generally, we download most of the things from the web and when we need to find them after some days it is sometimes hard.
So, what my script does will separate the files in a different folder like music files in one folder documents in another, and all other extensions like .exe .zip accordingly

## Instructions

- Create a new folder for your script and the file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by chauhanarpit09** [comment] 2021-08-22 04:26
Please assign this issue to me. :-)

**Comment by pawangeek** [comment] 2021-08-22 17:08
Duplicate of #219

**Closed by pawangeek** 2021-08-22 17:08 UTC
Labels: good first issue, up-for-grabs
