### ISSUE TITLE
Add a Hacker News Scraper script.

### ISSUE THREAD

**Issue by kshittijagrawal** [python-geeks/Automation-scripts#625] opened 2021-10-05 11:58 UTC
## Script Title - hackernews_scraper

**Brief** - A script that scrapes the exact count of news that the user demands and stores it in a csv file.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by kshittijagrawal** [comment] 2021-10-05 11:58
Hey @pawangeek !
Can I work on this script?

**Comment by pawangeek** [comment] 2021-10-05 12:01
possible duplicate of #548

**Comment by kshittijagrawal** [comment] 2021-10-05 12:23
Oh
Sorry I didn't notice. Let me edit the issue.

**Closed** 2021-10-06 05:17 UTC
Labels: good first issue, hacktoberfest, up-for-grabs
