### ISSUE TITLE
URL/Domain Extractor

### ISSUE THREAD

**Issue by RaveenaBhasin** [python-geeks/Automation-scripts#668] opened 2021-10-07 08:39 UTC
## Script Title - URL/Domain Extractor

Using this application user will be able to extract all types of URL, either be https, www, or any html or jpg url from the given text or documents. Also will allow user to extract all the domains present.
I will be using regex library for extracting urls and domains.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by pawangeek** [comment] 2021-10-07 09:23
Duplicate of #61

**Closed by pawangeek** 2021-10-07 09:23 UTC
Labels: good first issue, hacktoberfest, up-for-grabs
