### ISSUE TITLE
Grayscale Image Filter

### ISSUE THREAD

**Issue by ParadoxPD** [python-geeks/Automation-scripts#669] opened 2021-10-07 08:43 UTC
## Script Title - Grayscale Image Filter

**Brief** - A filter to convert ***rgb*** images to ***grayscale***

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a README.md in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by ParadoxPD** [comment] 2021-10-07 08:43
Assign this to me.

**Comment by pawangeek** [comment] 2021-10-07 09:25
Duplicate of #57

**Closed as completed by pawangeek** 2021-10-07 09:25 UTC
Labels: duplicate
