### ISSUE TITLE
Autotyper Script using Python

### ISSUE THREAD

**Issue by thechiranjeevvyas** [python-geeks/Automation-scripts#1000] opened 2024-10-14 15:32 UTC
## Script Title - Autotyper using pyautogui 

**Brief** 
A Python script that reads from a text file and simulates keyboard typing, automatically typing the content wherever the cursor is focused. The script leverages the `pyautogui` library to control the keyboard actions and the `time` library to add delays between keystrokes, mimicking natural typing behavior.

## Instructions

- Create a new folder for your script and file/folder name should be appropriate.
- Create a `README.md` (**[using this template](https://github.com/python-geeks/Automation-scripts/blob/main/README_TEMPLATE.md)**) in your folder for program Instructions
- add requirements.txt if needed

### Programming Language

- [x] Python

Happy Coding

**Comment by KrinsKumar** [comment] 2024-10-14 17:07
Hey can I work on this, If yes please assign this to me!

**Comment by pawangeek** [comment] 2024-10-15 06:11
Duplicate of [this](https://github.com/python-geeks/Automation-scripts/tree/main/auto_typer)

**Closed by pawangeek** 2024-10-15 06:11 UTC
Labels: duplicate
